export type UserInfo = {
    id: string,
    createdAt?: string,
    updatedAt?: string,
    deletedAt?: string,
    nickname?: string,
    account: string,
    email?: string,
    password?: string,
    userType?: number,
    userStatus?: number,
    mobile?: string,
    avatar?: string,
    bio?: string,
    token?: string,
}