/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectionHandle: typeof import('./src/components/collection/CollectionHandle.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NInput: typeof import('naive-ui')['NInput']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/public/SvgIcon.vue')['default']
    TableDemo: typeof import('./src/components/public/TableDemo.vue')['default']
    Vditor: typeof import('./src/components/Vditor.vue')['default']
  }
}
